//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int ID_Complaint { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public string IssueDescription { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string Status { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
