//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class D1E : DbContext
    {
        public D1E()
            : base("name=D1E")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Complaints> Complaints { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ServiceRequests> ServiceRequests { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
