//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequests
    {
        public int ID_ServiceRequest { get; set; }
        public Nullable<int> ID_Equipment { get; set; }
        public string ServiceType { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public string Executor { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
